spring: 
  application: 
    name: Pessoa
  datasource:
    url: jdbc:h2:mem:pessoa 
    username: sa 
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    show-sql: true
    properties:
      
      hibernate:
        format_sql:true
        use_sql_comments:true
        
  h2:
    console:
      enabled:  true
      path: /h2-console

logging:
  level:
    org.hibernate.sql: DEBUG
        

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  version: 1.0.0
  info:
    title: API de Cadastro de Pessoas
    description: API CRUD para gerenciamento de informações pessoais e endereços.
    version: v1
